name: 'Wulfland Action'
description: 'Get started with Container actions'
author: '@wulfland'
branding:
  icon: 'award'  
  color: 'green'
inputs: 
  myInput:
    description: 'Input to use'
    default: 'world'
outputs:
  time: 
    description: 'Current time'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.myInput }}
  env:
    VARIABLE1: ${{ inputs.myInput }}

