name: Test Action

on: [workflow_dispatch, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - name: Run my own container action
        id: hello-action
        uses: ./
        with:
          myInput: '@wulfland'
      - name: Output time set in the container
        run: echo "The time in the container was ${{ steps.hello-action.outputs.time }}"
